/* !!!! Autogenerated file, do not modify! */

#define QUAD_DIM 12

double quad_pts[12][2] = { { 0.06751786707392436, 0.8700998678316848 },
                           { 0.3215024938520156, 0.6232720494910644 },
                           { 0.660949196186798, 0.30472650086810704 },
                           { 0.277716166976405, 0.20644149866999495 },
                           { 0.06238226509439084, 0.06751786707392436 },
                           { 0.05522545665692, 0.3215024938520156 },
                           { 0.03432430294509488, 0.660949196186798 },
                           { 0.5158423343536, 0.277716166976405 },
                           { 0.8700998678316848, 0.06238226509439084 },
                           { 0.6232720494910644, 0.05522545665692 },
                           { 0.30472650086810704, 0.03432430294509488 },
                           { 0.20644149866999495, 0.5158423343536 } };

double weights[12] = { 0.053034056314869,   0.08776281742889622,
                       0.05755008556995056, 0.13498637401961758,
                       0.053034056314869,   0.08776281742889622,
                       0.05755008556995056, 0.13498637401961758,
                       0.053034056314869,   0.08776281742889622,
                       0.05755008556995056, 0.13498637401961758 };

void
compute_first_derivatives_C(double cp3d[10][3],
                            double s,
                            double t,
                            double f1[2][3])
{
  double x0 = 6 * s * t;
  double x1 = 3 * (s * s);
  double x2 = 3 * (t * t);
  double x3 = 6 * s + 6 * t - 6;
  double x4 = t * x3;
  double x5 = -s - t + 1;
  double x6 = 3 * (x5 * x5);
  double x7 = -x6 * cp3d[0][0];
  double x8 = -6 * t * x5;
  double x9 = -x0 - x8;
  double x10 = -6 * s * x5;
  double x11 = -x1 - x10;
  double x12 = s * x3;
  double x13 = x12 + x6;
  double x14 = -x6 * cp3d[0][1];
  double x15 = -x6 * cp3d[0][2];
  double x16 = -x0 - x10;
  double x17 = -x2 - x8;
  double x18 = x4 + x6;
  f1[0][0] = x0 * cp3d[8][0] + x1 * cp3d[9][0] + x11 * cp3d[7][0] +
             x13 * cp3d[4][0] - x2 * cp3d[2][0] + x2 * cp3d[6][0] +
             x4 * cp3d[1][0] + x7 + x9 * cp3d[5][0];
  f1[0][1] = x0 * cp3d[8][1] + x1 * cp3d[9][1] + x11 * cp3d[7][1] +
             x13 * cp3d[4][1] + x14 - x2 * cp3d[2][1] + x2 * cp3d[6][1] +
             x4 * cp3d[1][1] + x9 * cp3d[5][1];
  f1[0][2] = x0 * cp3d[8][2] + x1 * cp3d[9][2] + x11 * cp3d[7][2] +
             x13 * cp3d[4][2] + x15 - x2 * cp3d[2][2] + x2 * cp3d[6][2] +
             x4 * cp3d[1][2] + x9 * cp3d[5][2];
  f1[1][0] = x0 * cp3d[6][0] - x1 * cp3d[7][0] + x1 * cp3d[8][0] +
             x12 * cp3d[4][0] + x16 * cp3d[5][0] + x17 * cp3d[2][0] +
             x18 * cp3d[1][0] + x2 * cp3d[3][0] + x7;
  f1[1][1] = x0 * cp3d[6][1] - x1 * cp3d[7][1] + x1 * cp3d[8][1] +
             x12 * cp3d[4][1] + x14 + x16 * cp3d[5][1] + x17 * cp3d[2][1] +
             x18 * cp3d[1][1] + x2 * cp3d[3][1];
  f1[1][2] = x0 * cp3d[6][2] - x1 * cp3d[7][2] + x1 * cp3d[8][2] +
             x12 * cp3d[4][2] + x15 + x16 * cp3d[5][2] + x17 * cp3d[2][2] +
             x18 * cp3d[1][2] + x2 * cp3d[3][2];
}

void
compute_second_derivatives_C(double cp3d[10][3],
                             double s,
                             double t,
                             double f2[3][3])
{
  double x0 = 6 * s;
  double x1 = 6 * t;
  double x2 = 12 * t;
  double x3 = 3 * s;
  double x4 = t - 1;
  double x5 = -6 * x3 - 6 * x4;
  double x6 = -6 * s - 6 * x4;
  double x7 = x6 * cp3d[0][0];
  double x8 = 2 * t;
  double x9 = 6 * x3 + 6 * x8 - 12;
  double x10 = x6 * cp3d[0][1];
  double x11 = x6 * cp3d[0][2];
  double x12 = 12 * s;
  double x13 = 3 * t;
  double x14 = s - 1;
  double x15 = -6 * x13 - 6 * x14;
  double x16 = 2 * s;
  double x17 = 6 * x13 + 6 * x16 - 12;
  double x18 = 6 * x14 + 6 * x8;
  double x19 = 6 * x16 + 6 * x4;
  double x20 = -6 * x16 - 6 * x8 + 6;
  f2[0][0] = x0 * cp3d[9][0] + x1 * cp3d[1][0] + x1 * cp3d[8][0] -
             x2 * cp3d[5][0] + x5 * cp3d[7][0] + x7 + x9 * cp3d[4][0];
  f2[0][1] = x0 * cp3d[9][1] + x1 * cp3d[1][1] + x1 * cp3d[8][1] + x10 -
             x2 * cp3d[5][1] + x5 * cp3d[7][1] + x9 * cp3d[4][1];
  f2[0][2] = x0 * cp3d[9][2] + x1 * cp3d[1][2] + x1 * cp3d[8][2] + x11 -
             x2 * cp3d[5][2] + x5 * cp3d[7][2] + x9 * cp3d[4][2];
  f2[1][0] = x0 * cp3d[4][0] + x0 * cp3d[6][0] + x1 * cp3d[3][0] -
             x12 * cp3d[5][0] + x15 * cp3d[2][0] + x17 * cp3d[1][0] + x7;
  f2[1][1] = x0 * cp3d[4][1] + x0 * cp3d[6][1] + x1 * cp3d[3][1] + x10 -
             x12 * cp3d[5][1] + x15 * cp3d[2][1] + x17 * cp3d[1][1];
  f2[1][2] = x0 * cp3d[4][2] + x0 * cp3d[6][2] + x1 * cp3d[3][2] + x11 -
             x12 * cp3d[5][2] + x15 * cp3d[2][2] + x17 * cp3d[1][2];
  f2[2][0] = -x0 * cp3d[7][0] + x0 * cp3d[8][0] - x1 * cp3d[2][0] +
             x1 * cp3d[6][0] + x18 * cp3d[1][0] + x19 * cp3d[4][0] +
             x20 * cp3d[5][0] + x7;
  f2[2][1] = -x0 * cp3d[7][1] + x0 * cp3d[8][1] - x1 * cp3d[2][1] +
             x1 * cp3d[6][1] + x10 + x18 * cp3d[1][1] + x19 * cp3d[4][1] +
             x20 * cp3d[5][1];
  f2[2][2] = -x0 * cp3d[7][2] + x0 * cp3d[8][2] - x1 * cp3d[2][2] +
             x1 * cp3d[6][2] + x11 + x18 * cp3d[1][2] + x19 * cp3d[4][2] +
             x20 * cp3d[5][2];
}

void
compute_EFG_C(double f1[2][3], double f2[3][3], double EFG[3][3])
{
  double x0 = f1[0][0] * f2[2][0];
  double x1 = f1[0][1] * f2[2][1];
  double x2 = f1[0][2] * f2[2][2];
  double x3 = f1[1][0] * f2[2][0];
  double x4 = f1[1][1] * f2[2][1];
  double x5 = f1[1][2] * f2[2][2];
  EFG[0][0] = f1[0][0] * f1[0][0] + f1[0][1] * f1[0][1] + f1[0][2] * f1[0][2];
  EFG[0][1] = f1[0][0] * f1[1][0] + f1[0][1] * f1[1][1] + f1[0][2] * f1[1][2];
  EFG[0][2] = f1[1][0] * f1[1][0] + f1[1][1] * f1[1][1] + f1[1][2] * f1[1][2];
  EFG[1][0] =
    2 * f1[0][0] * f2[0][0] + 2 * f1[0][1] * f2[0][1] + 2 * f1[0][2] * f2[0][2];
  EFG[1][1] = x0 + x1 + x2 + f1[1][0] * f2[0][0] + f1[1][1] * f2[0][1] +
              f1[1][2] * f2[0][2];
  EFG[1][2] = 2 * x3 + 2 * x4 + 2 * x5;
  EFG[2][0] = 2 * x0 + 2 * x1 + 2 * x2;
  EFG[2][1] = x3 + x4 + x5 + f1[0][0] * f2[1][0] + f1[0][1] * f2[1][1] +
              f1[0][2] * f2[1][2];
  EFG[2][2] =
    2 * f1[1][0] * f2[1][0] + 2 * f1[1][1] * f2[1][1] + 2 * f1[1][2] * f2[1][2];
}

void
compute_LB_coeffs_C(double EFG[3][3], double LB_coeffs[5])
{
  double x0 = EFG[0][1] * EFG[0][1];
  double x1 = EFG[0][0] * EFG[0][0];
  double x2 = EFG[0][2] * EFG[0][2];
  double x3 = EFG[0][0] * EFG[0][2];
  double x4 = 1.0 / (-4 * x0 * x3 + 2 * x1 * x2 +
                     2 * (EFG[0][1] * EFG[0][1] * EFG[0][1] * EFG[0][1]));
  double x5 = EFG[0][0] * EFG[0][1];
  double x6 = x4 * EFG[1][2];
  double x7 = x4 * EFG[2][0];
  double x8 = EFG[0][1] * EFG[0][2];
  double x9 = 2 * EFG[0][1];
  double x10 = x4 * x9;
  double x11 = 1.0 / (-x0 + x3);
  LB_coeffs[0] = 2 * x0 * x4 * EFG[1][2] - x10 * EFG[0][2] * EFG[1][1] +
                 x2 * x4 * EFG[1][0] - x3 * x6 - x4 * x5 * EFG[2][2] +
                 2 * x4 * EFG[0][0] * EFG[0][2] * EFG[2][1] - x7 * x8;
  LB_coeffs[1] = 2 * x0 * x4 * EFG[2][0] + x1 * x4 * EFG[2][2] -
                 x10 * EFG[0][0] * EFG[2][1] - x3 * x7 - x4 * x8 * EFG[1][0] +
                 2 * x4 * EFG[0][0] * EFG[0][2] * EFG[1][1] - x5 * x6;
  LB_coeffs[2] = -x11 * EFG[0][2];
  LB_coeffs[3] = -x11 * EFG[0][0];
  LB_coeffs[4] = x11 * x9;
}

void
compute_LB_of_basis_C(double LBc[5], double s, double t, double LB_of_basis[10])
{
  double x0 = s - 1;
  double x1 = -t - x0;
  double x2 = 6 * x1;
  double x3 = 3 * (x1 * x1);
  double x4 = 6 * t;
  double x5 = x4 * LBc[2];
  double x6 = 2 * t;
  double x7 = 6 * LBc[4];
  double x8 = 3 * t;
  double x9 = 2 * s;
  double x10 = x9 - 2;
  double x11 = 6 * LBc[3];
  double x12 = x10 + x6;
  double x13 = x12 * x8;
  double x14 = 3 * (t * t);
  double x15 = -6 * t * x1;
  double x16 = x14 * LBc[0] + x4 * LBc[4];
  double x17 = s * x11;
  double x18 = x9 - 1;
  double x19 = 3 * s;
  double x20 = 6 * LBc[2];
  double x21 = x12 * x19;
  double x22 = s * x4;
  double x23 = -6 * s * x1;
  double x24 = 3 * (s * s);
  double x25 = s * x7 + x24 * LBc[1];
  LB_of_basis[0] =
    x2 * LBc[2] + x2 * LBc[3] + x2 * LBc[4] - x3 * LBc[0] - x3 * LBc[1];
  LB_of_basis[1] =
    x11 * (x10 + x8) + x13 * LBc[0] + x5 + x7 * (x0 + x6) + (x13 + x3) * LBc[1];
  LB_of_basis[2] = -x16 + 6 * (-x0 - x8) * LBc[3] + (-x14 - x15) * LBc[1];
  LB_of_basis[3] = x14 * LBc[1] + x4 * LBc[3];
  LB_of_basis[4] = x17 + x20 * (x19 + x6 - 2) + x21 * LBc[1] + x7 * (t + x18) +
                   (x21 + x3) * LBc[0];
  LB_of_basis[5] = -12 * s * LBc[3] - 12 * t * LBc[2] + x7 * (-x18 - x6) +
                   (-x15 - x22) * LBc[0] + (-x22 - x23) * LBc[1];
  LB_of_basis[6] = x16 + x17 + x22 * LBc[1];
  LB_of_basis[7] = -x25 + (-x23 - x24) * LBc[0] + 6 * (-t - x19 + 1) * LBc[2];
  LB_of_basis[8] = x22 * LBc[0] + x25 + x5;
  LB_of_basis[9] = s * x20 + x24 * LBc[0];
}

void
compute_LB_of_basis_cp_C(double cp_3d[10][3],
                         double s,
                         double t,
                         double* W,
                         double LB_of_basis[10])
{
  double f1[2][3];
  double f2[3][3];
  double EFG[3][3];
  double LB_coeffs[5];

  compute_first_derivatives_C(cp_3d, s, t, f1);
  compute_second_derivatives_C(cp_3d, s, t, f2);
  compute_EFG_C(f1, f2, EFG);
  compute_LB_coeffs_C(EFG, LB_coeffs);
  compute_LB_of_basis_C(LB_coeffs, s, t, LB_of_basis);
  *W = EFG[0][0] * EFG[0][2] - EFG[0][1] * EFG[0][1];
}

#include <math.h>
void
compute_elem_matrix_C(double cp_3d[10][3],
                      int quad_dim,
                      double quad_pts[][2],
                      double weights[],
                      double A[10][10])
{
  int i, j, m;
  double LB_of_basis[quad_dim][10];
  double W[quad_dim];
  for (m = 0; m < quad_dim; m++) {
    compute_LB_of_basis_cp_C(
      cp_3d, quad_pts[m][0], quad_pts[m][1], &(W[m]), LB_of_basis[m]);
  }

  for (i = 0; i < 10; i++) {
    for (j = 0; j < 10; j++) {
      A[i][j] = 0.0;
      for (m = 0; m < quad_dim; m++) {
        A[i][j] +=
          LB_of_basis[m][i] * LB_of_basis[m][j] * weights[m] * sqrt(W[m]);
      }
    }
  }
}
