/* !!!! Autogenerated file, do not modify! */

#define QUAD_DIM 12
#include "autodiff.h"

//typedef DScalar2<double,  Eigen::Matrix<double, 30, 1>, Eigen::Matrix<double, 30, 30>> DiffScalar;
//typedef DScalar<double,  Eigen::Matrix<double, 30, 1>> DiffScalar;

template <typename DiffScalar>
void compute_first_derivatives_C (
  DiffScalar cp_3d[10][3],
  double s,
  double t,
  DiffScalar f1[2][3])
{
  f1[0][0] = (-0.3e1 * cp_3d[0][0] + 0.6e1 * cp_3d[1][0] - 0.3e1 * cp_3d[2][0] + 0.3e1 * cp_3d[4][0] - 0.6e1 * cp_3d[5][0] + 0.3e1 * cp_3d[6][0]) * t * t + ((0.6e1 * cp_3d[8][0] - 0.6e1 * cp_3d[0][0] + 0.6e1 * cp_3d[1][0] + 0.12e2 * cp_3d[4][0] - 0.12e2 * cp_3d[5][0] - 0.6e1 * cp_3d[7][0]) * s + 0.6e1 * cp_3d[0][0] - 0.6e1 * cp_3d[1][0] - 0.6e1 * cp_3d[4][0] + 0.6e1 * cp_3d[5][0]) * t + (0.3e1 * cp_3d[9][0] - 0.3e1 * cp_3d[0][0] + 0.9e1 * cp_3d[4][0] - 0.9e1 * cp_3d[7][0]) * s * s + (0.6e1 * cp_3d[0][0] - 0.12e2 * cp_3d[4][0] + 0.6e1 * cp_3d[7][0]) * s - 0.3e1 * cp_3d[0][0] + 0.3e1 * cp_3d[4][0];
  f1[0][1] = (-0.3e1 * cp_3d[0][1] + 0.6e1 * cp_3d[1][1] - 0.3e1 * cp_3d[2][1] + 0.3e1 * cp_3d[4][1] - 0.6e1 * cp_3d[5][1] + 0.3e1 * cp_3d[6][1]) * t * t + ((0.6e1 * cp_3d[8][1] - 0.6e1 * cp_3d[0][1] + 0.6e1 * cp_3d[1][1] + 0.12e2 * cp_3d[4][1] - 0.12e2 * cp_3d[5][1] - 0.6e1 * cp_3d[7][1]) * s + 0.6e1 * cp_3d[0][1] - 0.6e1 * cp_3d[1][1] - 0.6e1 * cp_3d[4][1] + 0.6e1 * cp_3d[5][1]) * t + (0.3e1 * cp_3d[9][1] - 0.3e1 * cp_3d[0][1] + 0.9e1 * cp_3d[4][1] - 0.9e1 * cp_3d[7][1]) * s * s + (0.6e1 * cp_3d[0][1] - 0.12e2 * cp_3d[4][1] + 0.6e1 * cp_3d[7][1]) * s - 0.3e1 * cp_3d[0][1] + 0.3e1 * cp_3d[4][1];
  f1[0][2] = (-0.3e1 * cp_3d[0][2] + 0.6e1 * cp_3d[1][2] - 0.3e1 * cp_3d[2][2] + 0.3e1 * cp_3d[4][2] - 0.6e1 * cp_3d[5][2] + 0.3e1 * cp_3d[6][2]) * t * t + ((0.6e1 * cp_3d[8][2] - 0.6e1 * cp_3d[0][2] + 0.6e1 * cp_3d[1][2] + 0.12e2 * cp_3d[4][2] - 0.12e2 * cp_3d[5][2] - 0.6e1 * cp_3d[7][2]) * s + 0.6e1 * cp_3d[0][2] - 0.6e1 * cp_3d[1][2] - 0.6e1 * cp_3d[4][2] + 0.6e1 * cp_3d[5][2]) * t + (0.3e1 * cp_3d[9][2] - 0.3e1 * cp_3d[0][2] + 0.9e1 * cp_3d[4][2] - 0.9e1 * cp_3d[7][2]) * s * s + (0.6e1 * cp_3d[0][2] - 0.12e2 * cp_3d[4][2] + 0.6e1 * cp_3d[7][2]) * s - 0.3e1 * cp_3d[0][2] + 0.3e1 * cp_3d[4][2];
  f1[1][0] = (-0.3e1 * cp_3d[7][0] + 0.3e1 * cp_3d[8][0] - 0.3e1 * cp_3d[0][0] + 0.3e1 * cp_3d[1][0] + 0.6e1 * cp_3d[4][0] - 0.6e1 * cp_3d[5][0]) * s * s + ((-0.6e1 * cp_3d[0][0] + 0.12e2 * cp_3d[1][0] - 0.6e1 * cp_3d[2][0] + 0.6e1 * cp_3d[4][0] - 0.12e2 * cp_3d[5][0] + 0.6e1 * cp_3d[6][0]) * t + 0.6e1 * cp_3d[0][0] - 0.6e1 * cp_3d[1][0] - 0.6e1 * cp_3d[4][0] + 0.6e1 * cp_3d[5][0]) * s + (-0.3e1 * cp_3d[0][0] + 0.9e1 * cp_3d[1][0] - 0.9e1 * cp_3d[2][0] + 0.3e1 * cp_3d[3][0]) * t * t + (0.6e1 * cp_3d[0][0] - 0.12e2 * cp_3d[1][0] + 0.6e1 * cp_3d[2][0]) * t - 0.3e1 * cp_3d[0][0] + 0.3e1 * cp_3d[1][0];
  f1[1][1] = (-0.3e1 * cp_3d[7][1] + 0.3e1 * cp_3d[8][1] - 0.3e1 * cp_3d[0][1] + 0.3e1 * cp_3d[1][1] + 0.6e1 * cp_3d[4][1] - 0.6e1 * cp_3d[5][1]) * s * s + ((-0.6e1 * cp_3d[0][1] + 0.12e2 * cp_3d[1][1] - 0.6e1 * cp_3d[2][1] + 0.6e1 * cp_3d[4][1] - 0.12e2 * cp_3d[5][1] + 0.6e1 * cp_3d[6][1]) * t + 0.6e1 * cp_3d[0][1] - 0.6e1 * cp_3d[1][1] - 0.6e1 * cp_3d[4][1] + 0.6e1 * cp_3d[5][1]) * s + (-0.3e1 * cp_3d[0][1] + 0.9e1 * cp_3d[1][1] - 0.9e1 * cp_3d[2][1] + 0.3e1 * cp_3d[3][1]) * t * t + (0.6e1 * cp_3d[0][1] - 0.12e2 * cp_3d[1][1] + 0.6e1 * cp_3d[2][1]) * t - 0.3e1 * cp_3d[0][1] + 0.3e1 * cp_3d[1][1];
  f1[1][2] = (-0.3e1 * cp_3d[7][2] + 0.3e1 * cp_3d[8][2] - 0.3e1 * cp_3d[0][2] + 0.3e1 * cp_3d[1][2] + 0.6e1 * cp_3d[4][2] - 0.6e1 * cp_3d[5][2]) * s * s + ((-0.6e1 * cp_3d[0][2] + 0.12e2 * cp_3d[1][2] - 0.6e1 * cp_3d[2][2] + 0.6e1 * cp_3d[4][2] - 0.12e2 * cp_3d[5][2] + 0.6e1 * cp_3d[6][2]) * t + 0.6e1 * cp_3d[0][2] - 0.6e1 * cp_3d[1][2] - 0.6e1 * cp_3d[4][2] + 0.6e1 * cp_3d[5][2]) * s + (-0.3e1 * cp_3d[0][2] + 0.9e1 * cp_3d[1][2] - 0.9e1 * cp_3d[2][2] + 0.3e1 * cp_3d[3][2]) * t * t + (0.6e1 * cp_3d[0][2] - 0.12e2 * cp_3d[1][2] + 0.6e1 * cp_3d[2][2]) * t - 0.3e1 * cp_3d[0][2] + 0.3e1 * cp_3d[1][2];
}

template <typename DiffScalar>
void compute_second_derivatives_C (
  DiffScalar cp_3d[10][3],
  double s,
  double t,
  DiffScalar f2[3][3])
{
  f2[0][0] = (0.6e1 * cp_3d[8][0] - 0.6e1 * cp_3d[0][0] + 0.6e1 * cp_3d[1][0] + 0.12e2 * cp_3d[4][0] - 0.12e2 * cp_3d[5][0] - 0.6e1 * cp_3d[7][0]) * t + (-0.6e1 * cp_3d[0][0] + 0.18e2 * cp_3d[4][0] - 0.18e2 * cp_3d[7][0] + 0.6e1 * cp_3d[9][0]) * s + 0.6e1 * cp_3d[0][0] - 0.12e2 * cp_3d[4][0] + 0.6e1 * cp_3d[7][0];
  f2[0][1] = (0.6e1 * cp_3d[8][1] - 0.6e1 * cp_3d[0][1] + 0.6e1 * cp_3d[1][1] + 0.12e2 * cp_3d[4][1] - 0.12e2 * cp_3d[5][1] - 0.6e1 * cp_3d[7][1]) * t + (-0.6e1 * cp_3d[0][1] + 0.18e2 * cp_3d[4][1] - 0.18e2 * cp_3d[7][1] + 0.6e1 * cp_3d[9][1]) * s + 0.6e1 * cp_3d[0][1] - 0.12e2 * cp_3d[4][1] + 0.6e1 * cp_3d[7][1];
  f2[0][2] = (0.6e1 * cp_3d[8][2] - 0.6e1 * cp_3d[0][2] + 0.6e1 * cp_3d[1][2] + 0.12e2 * cp_3d[4][2] - 0.12e2 * cp_3d[5][2] - 0.6e1 * cp_3d[7][2]) * t + (-0.6e1 * cp_3d[0][2] + 0.18e2 * cp_3d[4][2] - 0.18e2 * cp_3d[7][2] + 0.6e1 * cp_3d[9][2]) * s + 0.6e1 * cp_3d[0][2] - 0.12e2 * cp_3d[4][2] + 0.6e1 * cp_3d[7][2];
  f2[1][0] = (-0.6e1 * cp_3d[0][0] + 0.12e2 * cp_3d[1][0] - 0.6e1 * cp_3d[2][0] + 0.6e1 * cp_3d[4][0] - 0.12e2 * cp_3d[5][0] + 0.6e1 * cp_3d[6][0]) * s + (-0.6e1 * cp_3d[0][0] + 0.18e2 * cp_3d[1][0] - 0.18e2 * cp_3d[2][0] + 0.6e1 * cp_3d[3][0]) * t + 0.6e1 * cp_3d[0][0] - 0.12e2 * cp_3d[1][0] + 0.6e1 * cp_3d[2][0];
  f2[1][1] = (-0.6e1 * cp_3d[0][1] + 0.12e2 * cp_3d[1][1] - 0.6e1 * cp_3d[2][1] + 0.6e1 * cp_3d[4][1] - 0.12e2 * cp_3d[5][1] + 0.6e1 * cp_3d[6][1]) * s + (-0.6e1 * cp_3d[0][1] + 0.18e2 * cp_3d[1][1] - 0.18e2 * cp_3d[2][1] + 0.6e1 * cp_3d[3][1]) * t + 0.6e1 * cp_3d[0][1] - 0.12e2 * cp_3d[1][1] + 0.6e1 * cp_3d[2][1];
  f2[1][2] = (-0.6e1 * cp_3d[0][2] + 0.12e2 * cp_3d[1][2] - 0.6e1 * cp_3d[2][2] + 0.6e1 * cp_3d[4][2] - 0.12e2 * cp_3d[5][2] + 0.6e1 * cp_3d[6][2]) * s + (-0.6e1 * cp_3d[0][2] + 0.18e2 * cp_3d[1][2] - 0.18e2 * cp_3d[2][2] + 0.6e1 * cp_3d[3][2]) * t + 0.6e1 * cp_3d[0][2] - 0.12e2 * cp_3d[1][2] + 0.6e1 * cp_3d[2][2];
  f2[2][0] = (0.6e1 * cp_3d[8][0] - 0.6e1 * cp_3d[0][0] + 0.6e1 * cp_3d[1][0] + 0.12e2 * cp_3d[4][0] - 0.12e2 * cp_3d[5][0] - 0.6e1 * cp_3d[7][0]) * s + (-0.6e1 * cp_3d[0][0] + 0.12e2 * cp_3d[1][0] - 0.6e1 * cp_3d[2][0] + 0.6e1 * cp_3d[4][0] - 0.12e2 * cp_3d[5][0] + 0.6e1 * cp_3d[6][0]) * t + 0.6e1 * cp_3d[0][0] - 0.6e1 * cp_3d[1][0] - 0.6e1 * cp_3d[4][0] + 0.6e1 * cp_3d[5][0];
  f2[2][1] = (0.6e1 * cp_3d[8][1] - 0.6e1 * cp_3d[0][1] + 0.6e1 * cp_3d[1][1] + 0.12e2 * cp_3d[4][1] - 0.12e2 * cp_3d[5][1] - 0.6e1 * cp_3d[7][1]) * s + (-0.6e1 * cp_3d[0][1] + 0.12e2 * cp_3d[1][1] - 0.6e1 * cp_3d[2][1] + 0.6e1 * cp_3d[4][1] - 0.12e2 * cp_3d[5][1] + 0.6e1 * cp_3d[6][1]) * t + 0.6e1 * cp_3d[0][1] - 0.6e1 * cp_3d[1][1] - 0.6e1 * cp_3d[4][1] + 0.6e1 * cp_3d[5][1];
  f2[2][2] = (0.6e1 * cp_3d[8][2] - 0.6e1 * cp_3d[0][2] + 0.6e1 * cp_3d[1][2] + 0.12e2 * cp_3d[4][2] - 0.12e2 * cp_3d[5][2] - 0.6e1 * cp_3d[7][2]) * s + (-0.6e1 * cp_3d[0][2] + 0.12e2 * cp_3d[1][2] - 0.6e1 * cp_3d[2][2] + 0.6e1 * cp_3d[4][2] - 0.12e2 * cp_3d[5][2] + 0.6e1 * cp_3d[6][2]) * t + 0.6e1 * cp_3d[0][2] - 0.6e1 * cp_3d[1][2] - 0.6e1 * cp_3d[4][2] + 0.6e1 * cp_3d[5][2];
}

template <typename DiffScalar>
void compute_EFG_C (DiffScalar f1[2][3], DiffScalar f2[3][3], DiffScalar EFG[3][3])
{
  EFG[0][0] = f1[0][0] * f1[0][0] + f1[0][1] * f1[0][1] + f1[0][2] * f1[0][2];
  EFG[0][1] = f1[0][0] * f1[1][0] + f1[0][1] * f1[1][1] + f1[0][2] * f1[1][2];
  EFG[0][2] = f1[1][0] * f1[1][0] + f1[1][1] * f1[1][1] + f1[1][2] * f1[1][2];
  EFG[1][0] = 0.2e1 * f1[0][0] * f2[0][0] + 0.2e1 * f1[0][1] * f2[0][1] + 0.2e1 * f1[0][2] * f2[0][2];
  EFG[1][1] = f1[0][0] * f2[2][0] + f1[0][1] * f2[2][1] + f1[0][2] * f2[2][2] + f1[1][0] * f2[0][0] + f1[1][1] * f2[0][1] + f1[1][2] * f2[0][2];
  EFG[1][2] = 0.2e1 * f1[1][0] * f2[2][0] + 0.2e1 * f1[1][1] * f2[2][1] + 0.2e1 * f1[1][2] * f2[2][2];
  EFG[2][0] = 0.2e1 * f1[0][0] * f2[2][0] + 0.2e1 * f1[0][1] * f2[2][1] + 0.2e1 * f1[0][2] * f2[2][2];
  EFG[2][1] = f1[0][0] * f2[1][0] + f1[0][1] * f2[1][1] + f1[0][2] * f2[1][2] + f1[1][0] * f2[2][0] + f1[1][1] * f2[2][1] + f1[1][2] * f2[2][2];
  EFG[2][2] = 0.2e1 * f1[1][0] * f2[1][0] + 0.2e1 * f1[1][1] * f2[1][1] + 0.2e1 * f1[1][2] * f2[1][2];
}
#include <math.h>

template <typename DiffScalar>
void compute_LB_coeffs_C (DiffScalar EFG[3][3], DiffScalar LB_coeffs[5])
{
  LB_coeffs[0] = (-EFG[0][0] * EFG[0][1] * EFG[2][2] - EFG[0][0] * EFG[0][2] * EFG[1][2] + 0.2e1 * EFG[0][0] * EFG[0][2] * EFG[2][1] + 0.2e1 * EFG[0][1] * EFG[0][1] * EFG[1][2] - 0.2e1 * EFG[0][1] * EFG[0][2] * EFG[1][1] - EFG[0][1] * EFG[0][2] * EFG[2][0] + EFG[0][2] * EFG[0][2] * EFG[1][0]) * pow(EFG[0][0] * EFG[0][2] - EFG[0][1] * EFG[0][1], -0.2e1) / 0.2e1;
  LB_coeffs[1] = (EFG[0][0] * EFG[0][0] * EFG[2][2] - EFG[0][0] * EFG[0][1] * EFG[1][2] - 0.2e1 * EFG[0][0] * EFG[0][1] * EFG[2][1] + 0.2e1 * EFG[0][0] * EFG[0][2] * EFG[1][1] - EFG[0][0] * EFG[0][2] * EFG[2][0] + 0.2e1 * EFG[0][1] * EFG[0][1] * EFG[2][0] - EFG[0][1] * EFG[0][2] * EFG[1][0]) * pow(EFG[0][0] * EFG[0][2] - EFG[0][1] * EFG[0][1], -0.2e1) / 0.2e1;
  LB_coeffs[2] = -0.1e1 / (EFG[0][0] * EFG[0][2] - EFG[0][1] * EFG[0][1]) * EFG[0][2];
  LB_coeffs[3] = -0.1e1 / (EFG[0][0] * EFG[0][2] - EFG[0][1] * EFG[0][1]) * EFG[0][0];
  LB_coeffs[4] = 0.2e1 / (EFG[0][0] * EFG[0][2] - EFG[0][1] * EFG[0][1]) * EFG[0][1];
}

template <typename DiffScalar>
void compute_LB_of_basis_C (
  DiffScalar LBc[5],
  double s,
  double t,
  DiffScalar LB_of_basis[10])
{
  DiffScalar t1;
  double t10;
  DiffScalar t12;
  DiffScalar t14;
  double t2;
  double t20;
  double t21;
  double t22;
  DiffScalar t25;
  DiffScalar t26;
  double t27;
  double t28;
  double t3;
  double t31;
  double t32;
  double t36;
  DiffScalar t38;
  DiffScalar t45;
  double t52;
  double t53;
  double t59;
  DiffScalar t6;
  DiffScalar t62;
  DiffScalar t63;
  double t64;
  double t68;
  double t83;
  DiffScalar t88;
  DiffScalar t9;
  DiffScalar t92;
  t1 = LBc[0];
  t2 = 0.1e1 - s - t;
  t3 = t2 * t2;
  t6 = LBc[1];
  t9 = LBc[2];
  t10 = 0.6e1 * t2;
  t12 = LBc[3];
  t14 = LBc[4];
  t20 = 0.3e1 * t3;
  t21 = t2 * t;
  t22 = 0.6e1 * t21;
  t25 = t * t9;
  t26 = 0.6e1 * t25;
  t27 = 0.12e2 * s;
  t28 = 0.18e2 * t;
  t31 = 0.6e1 * s;
  t32 = 0.12e2 * t;
  t36 = t * t;
  t38 = 0.3e1 * t36 * t1;
  t45 = 0.6e1 * t * t14;
  t52 = t2 * s;
  t53 = 0.6e1 * t52;
  t59 = 0.18e2 * s;
  t62 = s * t12;
  t63 = 0.6e1 * t62;
  t64 = 0.6e1 * t;
  t68 = s * t;
  t83 = s * s;
  t88 = 0.3e1 * t83 * t6;
  t92 = 0.6e1 * t14 * s;
  LB_of_basis[0] = -0.3e1 * t1 * t3 + t12 * t10 + t14 * t10 + t10 * t9 - 0.3e1 * t3 * t6;
  LB_of_basis[1] = -0.6e1 * t2 * t * t1 + (t20 - t22) * t6 + t26 + (-0.12e2 + t27 + t28) * t12 + (-0.6e1 + t31 + t32) * t14;
  LB_of_basis[2] = -t38 + (t22 - 0.3e1 * t36) * t6 + (0.6e1 - t31 - t28) * t12 - t45;
  LB_of_basis[3] = 0.6e1 * t * t12 + 0.3e1 * t36 * t6;
  LB_of_basis[4] = (t20 - t53) * t1 - 0.6e1 * t2 * s * t6 + (-0.12e2 + t59 + t32) * t9 + t63 + (-0.6e1 + t27 + t64) * t14;
  LB_of_basis[5] = (0.6e1 * t21 - 0.6e1 * t68) * t1 + (0.6e1 * t52 - 0.6e1 * t68) * t6 - 0.12e2 * t25 - 0.12e2 * t62 + (0.6e1 - t27 - t32) * t14;
  LB_of_basis[6] = 0.6e1 * t6 * t68 + t38 + t45 + t63;
  LB_of_basis[7] = (t53 - 0.3e1 * t83) * t1 - t88 + (0.6e1 - t59 - t64) * t9 - t92;
  LB_of_basis[8] = 0.6e1 * t1 * t68 + t26 + t88 + t92;
  LB_of_basis[9] = 0.6e1 * s * t9 + 0.3e1 * t1 * t83;
}

template <typename DiffScalar>
void compute_LB_of_basis_cp_C(DiffScalar cp_3d[10][3], double s, double t, DiffScalar* W, DiffScalar LB_of_basis[10]) { 
   DiffScalar f1[2][3]; 
   DiffScalar f2[3][3]; 
   DiffScalar EFG[3][3]; 
   DiffScalar LB_coeffs[5]; 

   compute_first_derivatives_C(cp_3d,s,t,f1); 
   compute_second_derivatives_C(cp_3d,s,t,f2); 
   compute_EFG_C(f1,f2,EFG); 
   compute_LB_coeffs_C(EFG,LB_coeffs); 
   compute_LB_of_basis_C(LB_coeffs, s,t, LB_of_basis);
   *W = EFG[0][0]*EFG[0][2]-EFG[0][1]*EFG[0][1];
}



#include <math.h>
template <typename DiffScalar>
void compute_elem_matrix_C(DiffScalar cp_3d[10][3], int quad_dim, double quad_pts[12][2], double weights[12], DiffScalar A[10][10]) {
   DiffScalar diff_quad_pts[12][2];
   DiffScalar diff_weights[12];
   for (int i = 0; i < 12; ++i) {
    diff_weights[i] = DiffScalar(weights[i]);
    for (int j = 0; j < 2; ++j) {
      diff_quad_pts[i][j] = DiffScalar(quad_pts[i][j]);
    } 
   }

   int i,j, m;
   DiffScalar LB_of_basis[QUAD_DIM][10]; 
   DiffScalar W[QUAD_DIM];
   for( m=0; m < quad_dim; m++) {
      compute_LB_of_basis_cp_C(cp_3d, quad_pts[m][0], quad_pts[m][1], &(W[m]), LB_of_basis[m] ); 
   }
   
   for( i = 0; i < 10; i++) { 
      for( j = 0; j < 10; j++) { 
          A[i][j] = 0.0;
          for( m = 0; m < quad_dim; m++) { 
              A[i][j] += LB_of_basis[m][i]*LB_of_basis[m][j]*weights[m]*sqrt(W[m]);
          } 
      } 
   }
}


